### ISSUE TITLE
rubydoc.info bei jedem Release aktualisieren

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/socha_ruby_client#10]
Hallo,

der Link unter Dokumentation auf github zeigt nicht auf die aktuelle gem version 1.2.1.

LG Kai Wollweber

**Comment by SKoschnicke** [comment]
Welcher Link genau? Ich habe gesehen, dass ich hier auf GitHub vergessen hatte, einen Release fuer 1.2.1 anzulegen (https://github.com/CAU-Kiel-Tech-Inf/socha_ruby_client/releases), das habe ich jetzt nachgeholt. Aber alle Links auf die Rubydoc Dokumentation die ich gefunden habe fuehren mich auf Version 1.2.1.

**Comment by SKoschnicke** [comment]
Ich denke ich habe den Link gefunden. Anscheinend aktualisiert rubydoc.info die Doku nicht sehr of selbst. Es gibt da einen Reload-Button mit dem man das manuell machen kann: http://www.rubydoc.info/find/github?q=socha_ruby_client ganz rechts. Eventuell kann man das in das Release-Script einbauen.

**Comment by SKoschnicke** [comment]
Danke fuer die Meldung!

**Comment by SKoschnicke** [comment]
Ich habe nun einen GitHub post-receive-hook eingerichtet, der die das Aktualisieren der Dokumentation auf rubydoc.info bewirken sollte. Mal sehen, ob das beim naechsten Update funktioniert.

**Comment by SKoschnicke** [comment]
Das funktioniert. Die Doku ist sofort auf dem neuesten Stand.
