### ISSUE TITLE
ruby client für die aktuelle Wettbewerbsrunde wird dringend benötigt

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/socha_ruby_client#11]
Hallo,

wir können mit unserer Gruppe der Peter-Ustinov-Schule nicht weiterarbeiten, solange noch kein simple client für ruby verfügbar ist.

Wie sieht der Stand der Entwicklung aus?

Viele Grüße

Kai Wollweber

**Comment by SKoschnicke** [comment]
Die Entwicklung hat sich leider durch einige andere Teilprojekte verzoegert. Ich arbeite aber jetzt wieder daran.

**Comment by SKoschnicke** [comment]
Der Client funktioniert jetzt ordnungsgemaess. Ich ergaenze morgen noch die Methodendokumentation und werde dann eine erste Version als Gem veroeffentlichen.

**Comment by SKoschnicke** [comment]
Die erste Version ist jetzt verfuegbar: https://rubygems.org/gems/software_challenge_client

RubyDocs zeigt im Moment noch einen Fehler, ich denke aber das wird sich nach einiger Zeit geben.
