### ISSUE TITLE
Fehler in Class: GameState #points_for_player(player) ⇒ Integer 

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/socha_ruby_client#12]
Spiel Mensch gegen manuell gestarteten Client:

Der Client (example) liefert bei dem ersten Aufruf der Methode move_requested einen Laufzeitfehler, der darauf zurückzuführen ist, dass die Methode GameState #points_for_player(player) ⇒ Integer 

in Zeile 18 abstürzt. Fehlerstack s. Anhang

[error-report.txt](https://github.com/CAU-Kiel-Tech-Inf/socha_ruby_client/files/2442740/error-report.txt)

**Comment by SKoschnicke** [comment]
Ist in der gerade veroeffentlichten Version 19.0.1 behoben.
